### ISSUE TITLE
NativeDroid causes different output after building NativeFlowBench apks

### ISSUE THREAD

**Issue by behnamben** [arguslab/NativeFlowBench#1]
Hi,  its been a time since i'm working on nativedroid and trying to add some futures to it.
but after generating some test cases and fail to detect sinks many time, i tried to just build your own benchmark with my android studio and generated a signed apk to test . but i dont know why this is not working too!
i added some logs to angr engine and i realized that it gave me different instructions from your apks. can someone help me and tell me what's the problem ? 
this is the output from nativedroid with your native_leak_array apk and mine built with android studio ndk v20:
your apk in the benchmark:
the call graph :
('cfggraph', NodeView((<CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x1638 0x1e01[2]>, <CFGNodeA GetStringUTFChars 0x40008f8L>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x2a 0x7f3[18]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x163b 0x1e04[8]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x14 0x7dd[16]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x28 0x7f1[2]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x24 0x7ed[4]>, <CFGNodeA AndroidLogPrint 0x1000028L>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send 0x7c9[20]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send-0xdd 0x6ecL[12]>, <CFGNodeA GetObjectArrayElement 0x4000918L>)))

COUNT CFG INSTRUCTIONS:
__android_log_print
<Block for 0x598, 12 bytes> 3
Java_org_arguslab_native_1leak_1array_MainActivity_send
<Block for 0x667, 2 bytes> 1
<Block for 0x669, 10 bytes> 4
<Block for 0x651, 8 bytes> 4
<Block for 0x673, 2 bytes> 1
<Block for 0x659, 14 bytes> 7
<Block for 0x639, 24 bytes> 12
__android_log_print
<Block for 0x1000010, 8 bytes> 2
GetStringUTFChars
<Block for 0x40008f8, 8 bytes> 2
GetObjectArrayElement
<Block for 0x4000918, 8 bytes> 2
Total INS: 38

my apk built with your code:
call graph:
('cfggraph', NodeView((<CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x18 0x651[8]>, <CFGNodeA AndroidLogPrint 0x1000010L>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x30 0x669[10]>, <CFGNodeA GetObjectArrayElement 0x4000918L>, <CFGNodeA 0x598[12]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x20 0x659[14]>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x3a 0x673[2]>, <CFGNodeA GetStringUTFChars 0x40008f8L>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send 0x639[24]>, <CFGNodeA 0x598[12]>, <CFGNodeA AndroidLogPrint 0x1000010L>, <CFGNodeA Java_org_arguslab_native_1leak_1array_MainActivity_send+0x2e 0x667[2]>)))

COUNT CFG INSTRUCTIONS:
Java_org_arguslab_native_1leak_1array_MainActivity_send
<Block for 0x1e01, 2 bytes> 1
<Block for 0x1e04, 8 bytes> 2
<Block for 0x7c9, 20 bytes> 9
<Block for 0x6ec, 12 bytes> 3
<Block for 0x7ed, 4 bytes> 2
<Block for 0x7f1, 2 bytes> 1
<Block for 0x7f3, 18 bytes> 7
<Block for 0x7dd, 16 bytes> 7
__android_log_print
GetStringUTFChars
<Block for 0x40008f8, 8 bytes> 2
GetObjectArrayElement
<Block for 0x4000918, 8 bytes> 2
Total INS: 36
is this because of different ndk versions?
thank you for your support!

**Comment by fgwei** [comment]
I think so, different ndk version might apply different compilation and optimization algorithms, thus the result might look different.

**Comment by behnamben** [comment]
can you tell me what was the exact ndk and cMake versions of your build?

**Comment by fgwei** [comment]
The building environment was on my old computer which I cannot recall the exact versions.
